(define (domain airline)
    (:requirements :typing)
    (:types city)
    (:predicates (plane-at ?x - city))
    (:functions (add-distance ?x - city ?y - city)
                (total-distance)
    )
    (:action fly :parameters (?x - city ?y - city)
                 :precondition (plane-at ?x)
                 :effect (and (plane-at ?y)
                                (not (plane-at ?x))
                                (increase (total-distance) (add-distance ?x ?y))
                         )
    )
)